// app/api/repos/[repoId]/pr/route.ts
import { NextRequest, NextResponse } from 'next/server'
import { auth, clerkClient } from '@clerk/nextjs/server'
import { db } from '@/lib/db'
import { repos } from '@/lib/schema'
import { eq } from 'drizzle-orm'
import { createPullRequestForFix, parseGitHubUrl } from '@/lib/github'

export async function POST(
 req: NextRequest, 
  // 1. Change repoId to id here to match the folder name [id]
  { params }: { params: Promise<{ id: string }> } 
) {
  const { userId } = await auth()
  if (!userId) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })

  // 2. Destructure 'id' and rename it to 'repoId' so you don't have to change any other code!
  const { id: repoId } = await params 
  
  const { filePath, refactoredCode, issue } = await req.json()

  try {
    // 1. Get Repo Details
    const repoRecs = await db.select().from(repos).where(eq(repos.id, repoId))
    const repoRecord = repoRecs[0]
    if (!repoRecord) throw new Error("Repository not found")

    const { owner, repo } = parseGitHubUrl(repoRecord.repoUrl)

    // 2. Fetch User's GitHub Token from Clerk
    const client = await clerkClient()
    const providerTokens = await client.users.getUserOauthAccessToken(userId, 'github')
    const token = providerTokens.data[0]?.token

    if (!token) {
      return NextResponse.json({ error: 'GitHub connection required. Please reconnect.' }, { status: 403 })
    }

    // 3. Define PR Metadata
    const commitMessage = `refactor: Auto-fix for ${filePath}`
    const prTitle = `🤖 RepoSage: AI Auto-Fix for ${filePath}`
    const prBody = `### AI Agent Fix\nThis PR was autonomously generated by **RepoSage Prime** to address the following health issue:\n\n> ${issue}\n\n**File Modified:** \`${filePath}\`\n\n*Please review the code before merging.*`

    // 4. Dispatch the Agent
    const prUrl = await createPullRequestForFix(
      owner, repo, filePath, refactoredCode, commitMessage, prTitle, prBody, token
    )

    return NextResponse.json({ prUrl })

  } catch (error) {
    console.error("Agent PR Error:", error)
    return NextResponse.json({ 
      error: error instanceof Error ? error.message : "Failed to generate Pull Request" 
    }, { status: 500 })
  }
}